import { organizePhotos, photoCategories } from "./product-categories";
const photo = (file, label, categories) => ({ src: `/imgs/sucursales/salcedo/${file}.webp`, label, categories });
const originalPhotos = [
  photo("DSC00460", "Cocinas y acabados para renovar tus espacios", ["Cocinas", "Pisos y revestimientos"]),
  photo("DSC00463", "Pisos, revestimientos y fregaderos", ["Pisos y revestimientos", "Cocinas"]),
  photo("DSC00466", "Exhibición de cocinas y fregaderos", ["Cocinas"]),
  photo("DSC00469", "Revestimientos e iluminación decorativa", ["Pisos y revestimientos", "Electricidad e iluminación"]),
  photo("DSC00475", "Grifería y duchas para baño y cocina", ["Grifería"]),
  photo("DSC00487", "Iluminación y material eléctrico", ["Electricidad e iluminación"]),
  photo("DSC00490", "Grifería y accesorios de baño", ["Grifería", "Baños y lavamanos"]),
  photo("DSC00493", "Accesorios y soluciones de ferretería", ["Ferretería"]),
  photo("DSC00499", "Pinturas y recubrimientos", ["Pintura y adhesivos"]),
  photo("DSC00502", "Herramientas y accesorios para cada tarea", ["Herramientas", "Ferretería"]),
  photo("DSC00511", "Herramientas manuales y productos de mantenimiento", ["Herramientas", "Ferretería"]),
  photo("DSC00514", "Exhibición de herramientas TOTAL", ["Herramientas"]),
  photo("DSC00517", "Herramientas y equipos para tus proyectos", ["Herramientas"]),
  photo("DSC00520", "Accesorios de ferretería y mantenimiento", ["Ferretería"]),
  photo("DSC00526", "Conexiones de plomería y calentadores de agua", ["Plomería y tubería"]),
  photo("DSC00529", "Conexiones y accesorios de tubería", ["Plomería y tubería"]),
  photo("DSC00532", "Adhesivos, selladores y productos para acabados", ["Pintura y adhesivos"]),
  photo("DSC00535", "Tubería y mangueras para tus instalaciones", ["Plomería y tubería"]),
  photo("DSC00544", "Herramientas y accesorios de trabajo", ["Herramientas", "Ferretería"]),
  photo("DSC00547", "Lavamanos y soluciones para baños", ["Baños y lavamanos"]),
  photo("DSC00550", "Artículos de jardín y limpieza", ["Jardín y limpieza"]),
  photo("DSC00553", "Escaleras, tubería y accesorios", ["Ferretería", "Plomería y tubería"]),
  photo("DSC00556", "Tubería y conexiones de plomería", ["Plomería y tubería"]),
  photo("DSC00559", "Equipos para construcción y trabajo en campo", ["Maquinaria"]),
  photo("DSC00562", "Maquinaria y equipos de compactación", ["Maquinaria"]),
  photo("DSC00565", "Sanitarios, lavamanos y acabados", ["Baños y lavamanos", "Pisos y revestimientos"]),
  photo("electricos-botarga", "Conoce nuestra línea de material eléctrico", ["Electricidad e iluminación"]),
  photo("bodega-botarga", "Varillas y materiales para construcción", ["Bodega y construcción"]),
  photo("DSC00589", "Mallas, tubería y cubiertas", ["Bodega y construcción"]),
  photo("DSC00592", "Bodega de materiales y acabados", ["Bodega y construcción"]),
  photo("DSC00595", "Mallas, cubiertas y materiales de obra", ["Bodega y construcción"]),
  photo("DSC00598", "Cemento, baldosas y tanques de agua", ["Bodega y construcción"]),
  photo("DSC00604", "Cubiertas, tubería y adhesivos para construcción", ["Bodega y construcción"]),
  photo("DSC00610", "Baldosas y revestimientos en bodega", ["Bodega y construcción"]),
  photo("DSC00613", "Mallas y tubería para construcción", ["Bodega y construcción"]),
];

export const salcedoPhotos = organizePhotos(originalPhotos);
export const salcedoCategories = photoCategories(salcedoPhotos);
